### ISSUE TITLE
Unit Test is dependent on actual API call.

### ISSUE THREAD

**Issue by davidlamys** [phuongdateh/SPWeather#1]
Hi James, 

https://github.com/phuongdateh/SPWeather/blob/9a97e53a34e45902dc3aea8f7a5e9a0be3697ed7/SPWeatherTests/Modules/Home/HomeInteractorTests.swift#L33

Perhaps you'd want to consider injecting the `WeatherApiServiceMock` like you did in the `WeatherDetailInteractorTests`. Or is this intentional?

**Comment by phuongddx** [comment]
Hi David, 

Good point for your review. When I update some testcase I missing this file. I have already update `HomeInteractorTests`.  👍
