### ISSUE TITLE
[UI Glitch] UI state resets when navigating from weather details

### ISSUE THREAD

**Issue by davidlamys** [phuongdateh/SPWeather#2]
1. search for a city
2. tap on city to view city detail
3. tap on back button
4. expect to be in search state

However if doing the steps for a city that is in history, it'd reset the order of the cities and also reset the search bar, leading to discontinuity. 
https://user-images.githubusercontent.com/1642110/223153734-058a120e-b366-4b7e-a223-086dff516c61.mp4

**Comment by phuongddx** [comment]
Nice point 👯 I have already updated. Now it working fine. Thanks you!
