### ISSUE TITLE
UITesting

### ISSUE THREAD

**Issue by davidlamys** [phuongdateh/SPWeather#7]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/1642110/223596142-8caed0e6-ef37-42ee-95b6-5633224ec54f.png">
I'm curious, how did you write UITest? (is it automated?) To my understanding I had to import `XCUIApplication` and if I can expand my knowledge that's great

**Comment by phuongddx** [comment]
Oh no so sorry @davidlamys, I tried to write the UITest but seem that it not working well. Then I was deleted it haha. Let me update the README.MD file. Whenever UITest working well I will show for you. So sorry!
